java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151018T1512\\best chromosome\\epoch-151\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151019T0743\\best chromosome\\epoch-209\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151020T0759\\best chromosome\\epoch-146\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151020T1934\\best chromosome\\epoch-50\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151021T0432\\best chromosome\\epoch-157\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151021T1556\\best chromosome\\epoch-99\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151022T0636\\best chromosome\\epoch-138\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151022T2149\\best chromosome\\epoch-31\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151023T1044\\best chromosome\\epoch-36\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151024T0321\\best chromosome\\epoch-237\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151026T0102\\best chromosome\\epoch-184\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151027T0345\\best chromosome\\epoch-55\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151027T1344\\best chromosome\\epoch-117\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151028T0313\\best chromosome\\epoch-109\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151028T1947\\best chromosome\\epoch-75\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151029T0649\\best chromosome\\epoch-205\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151029T1744\\best chromosome\\epoch-240\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151030T0346\\best chromosome\\epoch-28\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151030T1630\\best chromosome\\epoch-62\\chromosome.ser" &&
java -jar build\\libs\\hons-morphev-master-all.jar --fixing "..\\..\\results\\anchovy-20151031T0145\\best chromosome\\epoch-106\\chromosome.ser"
